acme_store:
    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
    prefix:   /

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /OC

#test_mongo:
#    resource: "@TestMongoBundle/Resources/config/routing.yml"
#    prefix:   /TestMongo

searchtweet:
    resource: "@SearchTweetBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
